name: movie_task_app
description: "A movie Flutter project."
publish_to: 'none'

environment:
  sdk: ">=3.5.4 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter_riverpod: ^2.3.6
  shared_preferences: ^2.5.3
  auto_route: ^8.1.3
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.5.0
  flutter_svg: ^2.0.15
  cached_network_image: ^3.3.1
  sqflite: ^2.3.3+1
  path: ^1.9.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  connectivity_plus: ^6.0.5
  share_plus: ^10.0.2
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^8.0.0
  retrofit_generator: ^8.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/svgs/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Regular.otf
        - asset: assets/fonts/inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.otf
          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
