import 'package:flutter/material.dart';
import 'app_colors.dart';

final appTextTheme = const TextTheme().copyWith(
  headlineLarge: const TextStyle(
    color: AppColors.primary,
    fontSize: 24,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w700,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  headlineMedium: const TextStyle(
    color: AppColors.primary,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w700,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  headlineSmall: const TextStyle(
    color: AppColors.primary,
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w700,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  displayLarge: const TextStyle(
    color: AppColors.primary,
    fontSize: 24,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w600,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  displayMedium: const TextStyle(
    color: AppColors.primary,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w600,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  displaySmall: const TextStyle(
    color: AppColors.primary,
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w600,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  titleLarge: const TextStyle(
    color: AppColors.primary,
    fontSize: 24,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w500,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  titleMedium: const TextStyle(
    color: AppColors.primary,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w500,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  labelLarge: const TextStyle(
    color: AppColors.primary,
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w500,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  bodyLarge: const TextStyle(
    color: AppColors.primary,
    fontSize: 24,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w400,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  bodyMedium: const TextStyle(
    color: AppColors.primary,
    fontSize: 18,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w400,
    letterSpacing: -0.30,
    height: 1.2,
  ),
  bodySmall: const TextStyle(
    color: AppColors.primary,
    fontSize: 12,
    fontFamily: 'Inter',
    fontWeight: FontWeight.w400,
    letterSpacing: -0.30,
    height: 1.2,
  ),

);
